---
Name: contactsconfig
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverCommerce\ContactAdmin\Extensions\ContactsAdminExtension
SilverStripe\Security\Member:
  extensions:
    - SilverCommerce\ContactAdmin\Extensions\MemberExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\ContactAdmin\Extensions\GroupExtension